import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "./globals.scss";

const geologica = Geologica({
    weight: ["400"],
    subsets: ["latin"],
    variable: "--font-geologica",
});

export const metadata: Metadata = {
    title: "Qwerty",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geologica.variable}`}>{children}</body>
        </html>
    );
}
